import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthProvider";
import Provider from "@/contexts/Provider";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Meetsup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-black/90`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider>
            <AuthProvider>{children}</AuthProvider>
          </Provider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
