import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Overview from "@/components/Overview";
import UsersList from "@/components/UsersList";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Meetsup",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.variable} antialiased h-full`}>
        <main className="fixed inset-3">
          <div className="grid grid-cols-12 grid-rows-20 gap-3 h-full">
            <Header />
            <UsersList />
            <Overview>{children}</Overview>
          </div>
        </main>
      </body>
    </html>
  );
}
